
title: FF8 Modding wiki
description: You will find here all info to mod your game
theme: just-the-docs

url: https://hobbitdur.github.io/FF8ModdingWiki

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/hobbitdur/FF8ModdingWiki

# Repository settings
github:
  # Replace with your GitHub username and repository name
  owner: hobbitdur
  repo: FF8ModdingWiki
  # Replace with the default branch (e.g., main, master)
  branch: main
  # Optional: Path to the docs folder if your Markdown files are in a subfolder
  path: ""
